config/routes.rb
Rails.application.routes.draw do
  root "books#index"
  patch "update_ratings", to: "books#update_ratings"

  get "rankings", to: "rankings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include BooksHelper

  def index
    @books = Book.order("RANDOM()").limit(2)
  end

  def update_ratings
    winner = Book.find(params[:winner_id])
    loser = Book.find(params[:loser_id])

    winner.update(rating: win(winner.rating, loser.rating))
    loser.update(rating: loss(loser.rating, winner.rating))

    respond_to do
    end
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def index
    @books = Book.all().sort_by(&:rating).reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def win_probability(book1, book2)
    (1 / (1 + (10 ** ((book2 - book1) / 400.0)))) * 100
  end

  def win(winner, loser)
    winner + (100 - win_probability(winner, loser))
  end

  def loss(loser, winner)
    loser + (0 - win_probability(loser, winner))
  end
end

app/helpers/rankings_helper.rb
module RankingsHelper
  def calculate_ranking(book, books)
    index = books.index(book)
    ranking = ((index.to_f / (books.size - 1)) * 100).round
    ranking.zero? ? 1 : ranking
  end
end

app/views/books/index.html.erb
<h1 style="text-align: center; margin: 30px; font-size: 28px; font-weight: normal; font-family: 'Trebuchet MS'">
  Would you rather read <b><%= @books[0].title %></b> or <b><%= @books[1].title %></b>?
</h1>

<div style="width: 100%; margin-top: 30px; display: flex; justify-content: center;">
  <div>
    <h1 style="font-family: 'Trebuchet MS'; font-size: 23px; text-align: center;"><%= @books[0].title %></h1>
    <%= button_to update_ratings_path(winner_id: @books[0].id, loser_id: @books[1].id), method: :patch, class: 'button' do %>
      <%= image_tag @books[0].image, width: '288px', height: '360px' %>
    <% end %>
    <% odds = win_probability(@books[0].rating, @books[1].rating).round %>
    <div style="margin-top: 10px; width: 280px;">
      <div style="display: flex; align-items: top;">
        <%= image_tag odds > 50 ? 'up_green_triangle.png' : odds < 50 ? 'down_red_triangle.png' : 'straight_gray_line.png', width: '25px', height: '20px' %>
        <span style="color: <%= odds > 50 ? 'green' : odds < 50 ? 'red' : 'gray' %>; margin-left: 10px; font-size: 18px; font-family: 'Trebuchet MS'">
          <%= "#{odds}% of users prefer #{@books[0].title}" %>
        </span>
      </div>
    </div>
  </div>

  <div style="margin-left: 80px;">
    <h1 style="font-family: 'Trebuchet MS'; font-size: 23px; text-align: center;"><%= @books[1].title %></h1>
    <%= button_to update_ratings_path(winner_id: @books[1].id, loser_id: @books[0].id), method: :patch, class: 'button' do %>
      <%= image_tag @books[1].image, width: '288px', height: '360px' %>
    <% end %>
    <% odds = win_probability(@books[1].rating, @books[0].rating).round %>
    <div style="margin-top: 10px; width: 280px;">
      <div style="display: flex; align-items: top;">
        <%= image_tag odds > 50 ? 'up_green_triangle.png' : odds < 50 ? 'down_red_triangle.png' : 'straight_gray_line.png', width: '25px', height: '20px' %>
        <span style="color: <%= odds > 50 ? 'green' : odds < 50 ? 'red' : 'gray' %>; width: 280px; margin-left: 10px; font-size: 18px; font-family: 'Trebuchet MS'">
          <%= "#{odds}% of users prefer #{@books[1].title}" %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rank The Book" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/books.png" type="image/png">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'navbar', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rankings/_card.html.erb
<div class="card" style="margin-top: 10px; width: 700px; background: #FFFFFF; border: 2px solid rgba(0, 0, 0, 0.12);">
  <div style="display: flex;">
    <%= image_tag book.image, alt: book.title, style: 'width: 130px; height: 163px;' %>
    <div style="font-family: 'Trebuchet MS'; font-size: 23px; line-height: 1.5; padding: 16px;">
      <b><%= book.title %></b><br/>
      <span style="font-size: 18px;">Ranked as <b>#<%= i+1 %></b> book</span><br/>
      <span style="font-size: 18px;">In top <b><%= calculate_ranking(book, books) %>%</b> of all books</span>
    </div>
  </div>
</div>

app/views/rankings/index.html.erb
<div class="books-container" style="display: flex; align-items: center; flex-direction: column;">
  <% @books.each_with_index do |book, i| %>
    <%= render partial: 'card', locals: { book: book, i: i, books: @books } %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <a class="navbar-brand" href="<%= root_path %>">Rank The Book</a>
  <ul class="navbar-nav">
    <li class="nav-item <%= 'active' if current_page?(root_path) %>">
      <%= link_to 'Home', root_path, class: 'nav-link' %>
    </li>
    <li class="nav-item <%= 'active' if current_page?(rankings_path) %>">
      <%= link_to 'Rankings', rankings_path, class: 'nav-link' %>
    </li>
  </ul>
</nav>